from Enemy import *
import random
class Zombiee(Enemy):
    def __init__(self, health_points, attack_damage):
        super().__init__(type_of_enemy="Zombiee", health_points=health_points, attack_damage=attack_damage)
        
    def talk(self):
        print("Spreads disease")
    
    def attack(self):
        print("attacks with zombiee goo")
        
    def special_attack(self):
        didSpecialAttackWork=random.random()<0.5
        if(didSpecialAttackWork):
            self.health_points+=2
            print("Zombiee health is regenerated by 2 points")